name: http_intercept_example
description: http_intercept_example
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.6.0
resolution: workspace
 
dependencies:
  flutter:
    sdk: flutter

  chopper: ^8.0.4
  cronet_http: ^1.3.2
  cupertino_http: ^2.0.2
  dio: ^5.7.0
  dio_compatibility_layer: ^0.1.0
  http: ^1.3.0
  http_cache:
    path: ../../http_cache
  http_image_provider: ^1.0.0
  http_intercept:
    path: ../../http_intercept
  http_logger:
    path: ../../http_logger
  json_annotation: ^4.9.0
  logging: ^1.3.0
  path_provider: ^2.1.5
  retrofit: ^4.4.2

dev_dependencies:
  build_runner: ^2.4.14
  chopper_generator: ^8.0.4
  json_serializable: ^6.9.3
  retrofit_generator: ^9.1.7
 
flutter:
  uses-material-design: true
