name: http_client_logger
description: >-
  Dart package that seamlessly adds HTTP traffic logging to 
  your Dart or Flutter project.
topics:
  - http
  - network
  - logging
version: 1.1.1
repository: https://github.com/ralph-bergmann/HttpTools
issue_tracker: https://github.com/ralph-bergmann/HttpTools/issues

environment:
  sdk: ^3.6.0
resolution: workspace

dependencies:
  async: ^2.12.0
  http: ^1.2.2
  http_client_interceptor: ^1.0.1
  logging: ^1.3.0
  meta: ^1.15.0

dev_dependencies:
  lints: ^6.0.0
