name: http_client_cache
description: >-
  Dart package that seamlessly adds HTTP traffic caching to 
  improve performance and reduce network load in Dart and 
  Flutter applications.
topics:
  - http
  - network
  - cache
version: 1.0.0
repository: https://github.com/ralph-bergmann/HttpTools
issue_tracker: https://github.com/ralph-bergmann/HttpTools/issues

environment:
  sdk: ^3.6.0
resolution: workspace

dependencies:
  async: ^2.11.0
  collection: ^1.19.0
  file: ^7.0.1
  fixnum: ^1.1.1
  http: ^1.2.2
  http_client_interceptor: ^1.0.1
  http_client_logger: ^1.0.0
  logging: ^1.3.0
  meta: ^1.15.0
  protobuf: ^3.1.0
  uuid: ^4.5.1

dev_dependencies:
  lints: ^5.1.1
  shelf: ^1.4.2
  shelf_test_handler: ^2.0.2
  test: ^1.25.14
