
name: http_cache_example
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: ^3.6.0
resolution: workspace

dependencies:
  http: ^1.3.0
  http_cache:
    path: ../../http_cache
  http_intercept:
    path: ../../http_intercept
  http_logger:
    path: ../../http_logger
  logging: ^1.3.0
  mime: ^2.0.0
