name: HttpTools

packages:
  - packages/**
  - packages/**/example/**

scripts:
  analyze:
    exec: dart analyze .

  fix:
    exec: dart fix --apply

  test:
    run: melos exec -c 1 --fail-fast -- "dart test"
    packageFilters:
      dirExists: test
      flutter: false
