name: http_tools
publish_to: none
repository: https://github.com/ralph-bergmann/HttpToolss
issue_tracker: https://github.com/ralph-bergmann/HttpTools/issues

environment:
  sdk: ^3.6.0

workspace:
  - packages/http_client_cache
  - packages/http_client_cache/example
  - packages/http_client_interceptor
  - packages/http_client_interceptor/example
  - packages/http_client_logger

dev_dependencies:
 melos: ^7.0.0-dev.7

melos:
  ide:
    intellij:
      enabled: false
  scripts:
    analyze:
      exec: dart analyze .
    format:
      exec: dart format -l 80 .
    fix:
      exec: dart fix --apply
    test:
      run: melos exec -c 1 --fail-fast -- "dart test"
      packageFilters:
        dirExists: test
        flutter: false
