name: http_intercept
description: >-
  A Dart package for intercepting and modifying HTTP requests and responses, 
  useful for logging, authentication, and error handling.
topics:
  - http
  - network
  - interceptor
  - middleware
  - error-handling
version: 1.0.1
repository: https://github.com/ralph-bergmann/HttpTools

environment:
  sdk: ^3.6.0
resolution: workspace

dependencies:
  collection: ^1.19.0
  http: ^1.2.2
  meta: ^1.15.0

dev_dependencies:
  lints: ^5.1.1
  shelf: ^1.4.2
  shelf_test_handler: ^2.0.2
  test: ^1.25.14
