name: http_logger
description: >-
  A Dart package for logging HTTP requests and responses.
topics:
  - http
  - network
  - logging
version: 1.0.0
repository: https://github.com/ralph-bergmann/HttpTools
issue_tracker: https://github.com/ralph-bergmann/HttpTools/issues

environment:
  sdk: ^3.6.0
resolution: workspace

dependencies:
  http: ^1.2.2
  http_intercept: ^1.0.1
  logging: ^1.3.0
  meta: ^1.15.0
  uuid: ^4.5.1

dev_dependencies:
  lints: ^5.1.1
