name: http_cache
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: ^3.6.0
resolution: workspace

dependencies:
  async: ^2.12.0
  collection: ^1.19.1
  file: ^7.0.1
  http: ^1.2.2
  http_intercept: ^1.0.0
  http_logger:
    git:
      url: https://github.com/ralph-bergmann/HttpTools.git
      ref: main
      path: packages/http_logger
  logging: ^1.3.0
  meta: ^1.15.0
  protobuf: ^3.1.0
  uuid: ^4.5.1

dev_dependencies:
  lints: ^5.1.1
  shelf: ^1.4.2
  shelf_test_handler: ^2.0.2
  test: ^1.25.14
