name: http_cache_example
description: http_cache_example
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.6.0
resolution: workspace

dependencies:
  http: ^1.3.0
  http_client_cache:
    path: ../../http_client_cache
  http_client_interceptor:
    path: ../../http_client_interceptor
  http_client_logger:
    path: ../../http_client_logger
  logging: ^1.3.0
  mime: ^2.0.0
